# Generated by Django 5.0.3 on 2024-03-24 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_course_active', models.BooleanField(default=True)),
                ('course_creation_date', models.DateField(auto_now_add=True)),
                ('course_name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('course_theme', models.CharField(max_length=100, verbose_name='Тематика курса')),
                ('course_description', models.TextField(verbose_name='Описание курса')),
                ('course_avatar', models.ImageField(blank=True, null=True, upload_to='course_avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])], verbose_name='Аватар Курса')),
                ('course_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course_students', models.ManyToManyField(blank=True, related_name='course_students', to=settings.AUTH_USER_MODEL, verbose_name='Ученики курса')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lesson_active', models.BooleanField(default=True)),
                ('lesson_creation_date', models.DateField(auto_now_add=True)),
                ('lesson_name', models.CharField(max_length=100, verbose_name='Название урока')),
                ('lesson_theme', models.CharField(max_length=100, verbose_name='Тематика урока')),
                ('lesson_description', models.TextField(verbose_name='Описание урока')),
                ('lesson_content', models.TextField(verbose_name='Содержание урока')),
                ('lesson_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
                ('lesson_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson_students', models.ManyToManyField(blank=True, related_name='lesson_students', to=settings.AUTH_USER_MODEL, verbose_name='Ученики урока')),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathersname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('musicedu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Музыкальное образование')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('profile_avatar', models.ImageField(blank=True, null=True, upload_to='profile_avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])], verbose_name='Аватар профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
