# Generated by Django 5.0.3 on 2024-04-06 07:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_courses_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание урока'),
        ),
    ]
