# Generated by Django 5.0.3 on 2024-04-14 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lesson_lesson_priority_courseprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_short', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('media', models.FileField(blank=True, null=True, upload_to='test_media/', verbose_name='Медиа')),
                ('type', models.CharField(choices=[('one', 'Один правильный ответ'), ('many', 'Несколько правильных ответов'), ('open', 'Развёрнутый ответ'), ('file', 'Ответ-файл'), ('note', 'Ноты')], default='one', max_length=100, verbose_name='Тип вопроса')),
                ('num_answers', models.IntegerField(verbose_name='Количество ответов')),
                ('answer1', models.CharField(max_length=100, verbose_name='Ответ 1')),
                ('answer2', models.CharField(max_length=100, verbose_name='Ответ 2')),
                ('answer3', models.CharField(max_length=100, verbose_name='Ответ 3')),
                ('answer4', models.CharField(max_length=100, verbose_name='Ответ 4')),
                ('answer5', models.CharField(max_length=100, verbose_name='Ответ 5')),
                ('answer6', models.CharField(max_length=100, verbose_name='Ответ 6')),
                ('answer7', models.CharField(max_length=100, verbose_name='Ответ 7')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('duration', models.IntegerField(verbose_name='Максимальная длительность ответа (в секундах)')),
                ('score', models.IntegerField(verbose_name='Баллы за задание')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.test'),
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('score', models.IntegerField(verbose_name='Баллы за ответ')),
                ('media', models.FileField(blank=True, null=True, upload_to='answer_media/', verbose_name='Медиа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testquestion')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='main.testquestion'),
        ),
    ]
