# Generated by Django 5.0.3 on 2024-04-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_testquestion_answer1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Отмечен'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы за ответ'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='num_answers',
            field=models.IntegerField(default=1, verbose_name='Количество ответов'),
        ),
    ]
