# Generated by Django 5.0.3 on 2024-04-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testanswer_checked_alter_testanswer_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
    ]
