# Generated by Django 5.0.3 on 2024-04-21 10:15

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testanswer_comment_alter_testquestion_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название нот')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ноты (json)')),
            ],
            options={
                'verbose_name': 'Ноты',
                'verbose_name_plural': 'Ноты',
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание урока'),
        ),
    ]
