# Generated by Django 5.0.3 on 2024-04-25 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_courses_course_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_avatar',
            field=models.ImageField(blank=True, default='course_avatars/istockphoto-1175435360-612x612.jpg', null=True, upload_to='course_avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])], verbose_name='Аватар Курса'),
        ),
    ]
