# Generated by Django 5.0.3 on 2024-04-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_testquestion_answer1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_creator',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_students',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_creator',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_students',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='test',
        ),
        migrations.DeleteModel(
            name='NoteSet',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testanswervariant',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='correct_answer',
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestAnswer',
        ),
        migrations.DeleteModel(
            name='TestAnswerVariant',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
