# Generated by Django 5.0.3 on 2024-04-30 06:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lesson_active', models.BooleanField(default=True)),
                ('lesson_creation_date', models.DateField(auto_now_add=True)),
                ('lesson_name', models.CharField(max_length=100, verbose_name='Название урока')),
                ('lesson_theme', models.CharField(max_length=100, verbose_name='Тематика урока')),
                ('lesson_description', models.TextField(verbose_name='Описание урока')),
                ('lesson_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание урока')),
                ('lesson_priority', models.IntegerField(blank=True, null=True, verbose_name='Приоритет урока')),
                ('lesson_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses')),
                ('lesson_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson_students', models.ManyToManyField(blank=True, related_name='lesson_students', to=settings.AUTH_USER_MODEL, verbose_name='Ученики урока')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
