# Generated by Django 5.0.3 on 2024-04-30 06:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_course_active', models.BooleanField(default=True, verbose_name='Курс активен')),
                ('course_creation_date', models.DateField(auto_now_add=True)),
                ('course_name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('course_theme', models.CharField(max_length=100, verbose_name='Тематика курса')),
                ('course_description', models.TextField(verbose_name='Описание курса')),
                ('course_avatar', models.ImageField(blank=True, default='course_avatars/istockphoto-1175435360-612x612.jpg', null=True, upload_to='course_avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])], verbose_name='Аватар Курса')),
                ('course_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course_students', models.ManyToManyField(blank=True, related_name='course_students', to=settings.AUTH_USER_MODEL, verbose_name='Ученики курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.IntegerField(blank=True, null=True, verbose_name='Номер урока в курсе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses')),
            ],
            options={
                'verbose_name': 'Прогресс прохождения курса',
                'verbose_name_plural': 'Прогресс прохождения курсов',
            },
        ),
    ]
