# Generated by Django 5.0.3 on 2024-05-07 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeedback',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
