# Generated by Django 5.0.3 on 2024-04-30 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название нот')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ноты (json)')),
            ],
            options={
                'verbose_name': 'Ноты',
                'verbose_name_plural': 'Ноты',
            },
        ),
        migrations.CreateModel(
            name='TestAnswerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_short', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('media', models.FileField(blank=True, null=True, upload_to='test_media/', verbose_name='Медиа')),
                ('type', models.CharField(choices=[('one', 'Один правильный ответ'), ('many', 'Несколько правильных ответов'), ('open', 'Развёрнутый ответ'), ('file', 'Ответ-файл'), ('note', 'Ноты')], default='one', max_length=100, verbose_name='Тип вопроса')),
                ('num_answers', models.IntegerField(default=1, verbose_name='Количество ответов')),
                ('duration', models.IntegerField(default=1, verbose_name='Максимальная длительность ответа (в секундах)')),
                ('score', models.IntegerField(verbose_name='Баллы за задание')),
                ('answers', models.ManyToManyField(blank=True, related_name='answers', to='tests.testanswervariant', verbose_name='Варианты ответов')),
                ('correct_answer', models.ManyToManyField(blank=True, null=True, related_name='correct_answer', to='tests.testanswervariant', verbose_name='Правильные ответы')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AddField(
            model_name='testanswervariant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testquestion'),
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы за ответ')),
                ('media', models.FileField(blank=True, null=True, upload_to='answer_media/', verbose_name='Медиа')),
                ('checked', models.BooleanField(default=False, verbose_name='Проверен')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testquestion')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
                ('questions', models.ManyToManyField(to='tests.testquestion')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
